### ISSUE TITLE
ch6.3 lack book.txt,body.txt

### ISSUE THREAD

**Issue by classifier001** [zhangkai-ai/build-kg-from-scratch#1]
trie_match.py
dict_name_list = ['book', 'body', 'blood_type', 'ethnic', 'country', 'occupation', 'country', 'city','constellation','position']

with open(dict_path + dict_name + '.txt', 'r', encoding='utf8') as f:

where is book.txt,body.txt etc ?

**Comment by winnie0** [comment]
The dictionary file has been added. :)
Please check the path: build-kg-from-scratch/ch6/6.3/kgqa/data/
