### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by SunYiLing123** [zhangkai-ai/build-kg-from-scratch#2]
requirements.txt 文件在哪？

**Comment by zhangkai-ai** [comment]
hi，不同小节的依赖库不同，位于各自小节目录中，按需安装，例如[6.4小节](https://github.com/zhangkai-ai/build-kg-from-scratch/blob/main/ch6/6.4/association/requirements.txt)

**Comment by ahjdzx** [comment]
6.3 没有 requirements.txt
还有依赖的数据怎么导入？
