### ISSUE TITLE
我在ch7中运行 python main_handler.py 出现报错如下：

### ISSUE THREAD

**Issue by SunYiLing123** [zhangkai-ai/build-kg-from-scratch#3]
d:\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
d:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
d:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "main_handler.py", line 7, in <module>
    from dm.dm_handler import dm_main_handler
  File "D:\build-kg-from-scratch-main\ch7\dm\dm_handler.py", line 8, in <module>
    from qa import bot_qa, common_qa, medicine_qa, user_qa, ir_qa, mr_qa
  File "D:\build-kg-from-scratch-main\ch7\qa\ir_qa.py", line 6, in <module>
    from util.es_util import es_object
  File "D:\build-kg-from-scratch-main\ch7\util\es_util.py", line 43, in <module>
    es_object = ESUtil("192.168.3.6", 9400)
  File "D:\build-kg-from-scratch-main\ch7\util\es_util.py", line 9, in __init__
    self.es = Elasticsearch(host=host, port=port, timeout=5, retry_on_timeout=False)
TypeError: __init__() got an unexpected keyword argument 'host'

**Comment by zhangkai-ai** [comment]
该问题是由于elasticsearch官方更新至8.x后，停止兼容了代码中的原有参数初始化
可以参考：[elasticsearch官方参考文档](https://elasticsearch-py.readthedocs.io/en/v8.1.3/api.html#cluster)
仓库代码已经更新：[地址](https://github.com/zhangkai-ai/build-kg-from-scratch/blob/main/ch7/util/es_util.py)，拉取后可解决版本不兼容报错问题
