### ISSUE TITLE
ch7：ModuleNotFoundError: No module named 'association'

### ISSUE THREAD

**Issue by lvjiujin** [zhangkai-ai/build-kg-from-scratch#4]
`
C:\Users\xx\Anaconda3\envs\torch_1.8_gpu\python.exe E:/Paper/NLP/知识图谱论文/build-kg-from-scratch/ch7/main_handler.py
Traceback (most recent call last):
  File "E:/Paper/NLP/kg/build-kg-from-scratch/ch7/main_handler.py", line 9, in <module>
    from dm.dm_handler import dm_main_handler
  File "E:\Paper\NLP\kg\build-kg-from-scratch\ch7\dm\dm_handler.py", line 9, in <module>
    from chat import hello_chat, association_chat
  File "E:\Paper\NLP\kg\build-kg-from-scratch\ch7\chat\association_chat.py", line 6, in <module>
    from association.main_handler import handler
ModuleNotFoundError: No module named 'association'
`

**Comment by lvjiujin** [comment]
I know, just command this line:
`
from association.main_handler import handler`
`

**Comment by zhangkai-ai** [comment]
the full version of association module is introduced in chapter 6.4, you can import the module from ch6 -> 6.4 -> association
the url is: [main_handler.py](https://github.com/zhangkai-ai/build-kg-from-scratch/blob/main/ch6/6.4/association/main_handler.py)
you may also notice that page.332 in the book has introduced this info

**Comment by lvjiujin** [comment]
> the full version of association module is introduced in chapter 6.4, you can import the module from ch6 -> 6.4 -> association the url is: [main_handler.py](https://github.com/zhangkai-ai/build-kg-from-scratch/blob/main/ch6/6.4/association/main_handler.py) you may also notice that page.332 in the book has introduced this info

Yes, this file is in the chapter 6.4.
