### ISSUE TITLE
ch6.3: ModuleNotFoundError: No module named 'marisa_trie'

### ISSUE THREAD

**Issue by lvjiujin** [zhangkai-ai/build-kg-from-scratch#5]
In the ch6.3 , when I run the command: python  kgqa.py then, it occurs the following error:

`
Traceback (most recent call last):
  File "E:/Paper/NLP/kig/build-kg-from-scratch/ch6/6.3/kgqa/kgqa.py", line 17, in <module>
    from util.trie_match import entity_trie
  File "E:\Paper\NLP\kg\build-kg-from-scratch\ch6\6.3\kgqa\util\trie_match.py", line 7, in <module>
    import marisa_trie
ModuleNotFoundError: No module named 'marisa_trie'
`
I noticed that there is no marisa_trie.py file in the util module.

**Comment by zhangkai-ai** [comment]
marisa_trie is a third-party dependency, use this command to install:

`pip install marisa-trie`

**Comment by lvjiujin** [comment]
> marisa_trie is a third-party dependency, use this command to install:
> 
> `pip install marisa-trie`

Thank you, I install it , it is ok!
