### ISSUE TITLE
您好，请问association_generator.py里的vec.bin文件是在哪生成的

### ISSUE THREAD

**Issue by cyw2016** [zhangkai-ai/build-kg-from-scratch#6]

**Comment by zhangkai-ai** [comment]
可参考p.319语义相似度 -> 词向量部分的内容，采用开源词向量模型，或者自行训练
例如[腾旭的开源词向量](https://ai.tencent.com/ailab/nlp/zh/download.html)

**Comment by cyw2016** [comment]
谢谢，我也下了这个语料库，对于机器学习这块才刚接触。主要是想跑起来ch7项目的对话看一下效果。

**Comment by cyw2016** [comment]
谢谢，我也下了这个语料库，对于机器学习这块才刚接触。主要是想跑起来ch7项目的对话看一下效果。

**Comment by cyw2016** [comment]
谢谢，我也下了这个语料库，对于机器学习这块才刚接触。主要是想跑起来ch7项目的对话看一下效果。
